name: Checks

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  typos:
    runs-on: ubuntu-latest
    name: spell check with typos
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run typos command
        shell: nix shell nixpkgs#typos --quiet --command bash {0}
        run: typos --hidden --exclude .git --format brief

  ruff:
    runs-on: ubuntu-latest
    name: lint and format by ruff
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run typos command
        shell: nix shell nixpkgs#ruff --quiet --command bash {0}
        run: |
          ruff format --check
          ruff check

  ty:
    runs-on: ubuntu-latest
    name: use ty to check types
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run typos command
        shell: nix shell nixpkgs#uv nixpkgs#ty --quiet --command bash {0}
        run: |
          uv sync
          ty check

  trivy-scan:
    name: use trivy to scan files
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Run Trivy vulnerability scanner in repo mode
        shell: nix shell nixpkgs#trivy --quiet --command bash {0}
        run: |
          trivy --quiet fs . \
            --output trivy-fs-results.sarif \
            --severity CRITICAL,HIGH,MEDIUM \
            --format sarif \
            --exit-code 1
          trivy --quiet config . \
            --output trivy-config-results.sarif \
            --severity CRITICAL,HIGH,MEDIUM \
            --format sarif \
            --exit-code 1
      - name: Upload "trivy fs" results to GitHub Security tab
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-fs-results.sarif
          category: trivy-fs-scan
      - name: Upload "trivy config" results to GitHub Security tab
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-config-results.sarif
          category: trivy-config-scan
